org: gaganserverless
service: water-quality-service

provider:
  name: aws
  runtime: nodejs20.x
  apiGateway:
    apiKeys:
      - waterApiKey
    usagePlan:
      quota:
        limit: 50000
        offset: 1
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: 
            - "arn:aws:dynamodb:*:*:table/*"

functions:
  labData:
    handler: dist/handlers/lab-data.handler
    events:
      - http:
          path: /lab-results
          method: post
          private: true
    environment:
      LAB_DATA_TABLE: lab-data
  sensorData:
    handler: dist/handlers/sensor-data.handler
    events:
      - http:
          path: /sensor-data
          method: post
          private: true
    environment:
      SENSOR_DATA_TABLE: sensor-data
  testKitData:
    handler: dist/handlers/test-kit-data.handler
    events:
      - http:
          path: /test-kits
          method: post
          private: true
    environment:
      TEST_KIT_DATA_TABLE: test-kit-data
  waterBot:
    handler: dist/handlers/water-quality-bot.handler
    environment:
      LAB_DATA_TABLE: lab-data
      SENSOR_DATA_TABLE: sensor-data
      TEST_KIT_DATA_TABLE: test-kit-data

resources:
  Resources:
    LabDataTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: dataid
            AttributeType: S
        KeySchema:
          -
            AttributeName: dataid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: lab-data
    SensorDataTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: dataid
            AttributeType: S
        KeySchema:
          -
            AttributeName: dataid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: sensor-data

    TestKitDataTable: 
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: dataid
            AttributeType: S
        KeySchema:
          -
            AttributeName: dataid
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: test-kit-data